# Storage Class for transmission app

kind: StorageClass
apiVersion: storage.k8s.io/v1

metadata:
  name: transm-storage-class

provisioner: k8s.io/minikube-hostpath
volumeBindingMode: Immediate

parameters:
 type: gp2 # This configures SSDs

allowVolumeExpansion: true
reclaimPolicy: Retain