#Transmission PV: config-pv

apiVersion: v1
kind: PersistentVolume

metadata:
  name: config-pv
  labels:
    type: local

spec:
  storageClassName: transm-storage-class
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/home/k8sadmin/transm_volume_files/config"
