# Transmission PVC: downloads-pvc

apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: downloads-pvc

spec:
  accessModes:
    - ReadWriteMany
  storageClassName: transm-storage-class
  resources:
    requests:
      storage: 5Gi